BIBDK2021-1505 handle FFU libraries
DBCDK/bibliotekdk-next-frontend pull request #1007
Opened 2023-10-17 14:29 UTC by mtni

https://dbcjira.atlassian.net/browse/BIBDK2021-1505
https://dbcjira.atlassian.net/browse/BIBDK2021-1647

2023-10-23 23:04 UTC, jonaspraem requested changes
Kun et par småting fra mig

2023-10-23 23:04 UTC, jonaspraem commented on src/components/_modal/pages/verify/Verify.page.js
> +    const hasBack = !!(index > 0);
!! udnødvendigt her? (index > 0) skulle gerne allerede være en true/false condition.

2023-10-23 23:04 UTC, jonaspraem commented on package.json
> +    "dev:next": "NODE_OPTIONS='--require ./logger' next -p ${PORT:-5000}",
Er det med vilje? ellers skal alle vidst lige være klar over hvorfor deres local ikke kører 3000 længere.

2023-10-24 06:33 UTC, mtni commented on package.json
> +    "dev:next": "NODE_OPTIONS='--require ./logger' next -p ${PORT:-5000}",
Hov den er smuttet, det er fordi jeg har kørt parallel med fbi-api.

2023-10-24 06:39 UTC, mtni commented on src/components/ffu/FFUListener.js
> +    // if user is signed in
Ja, jeg ville gerne have at det var nemt at læse og rette i, men jeg kan godt lave det med early returns istedet.

2023-10-24 06:43 UTC, mtni commented on src/components/base/translate/Translate.js
> +  return;
Den her bliver fjernet

2023-10-24 06:54 UTC, pjohans commented on src/components/_modal/pages/addLibrary/AddLibrary.page.js
> + * contains the login page for login modal
copy/paste .. login.js ??

2023-10-24 06:54 UTC, pjohans commented on src/components/_modal/pages/addLibrary/AddLibrary.page.js
> +export function AddLibrary({
en lille forklaring på hvad denher funktion gør

2023-10-24 07:00 UTC, pjohans commented on src/components/_modal/pages/removeLibrary/RemoveLibrary.js
> +import { useEffect } from "react";
@file - this file handles deletion of a library

2023-10-24 07:00 UTC, pjohans commented on src/components/_modal/pages/statusMessage/StatusMessage.js
> +import Top from "@/components/_modal/pages/base/top";
@file ....

2023-10-24 07:00 UTC, pjohans commented on src/components/_modal/pages/verify/Verify.page.js
> +import Text from "@/components/base/text";
@file ....

2023-10-24 07:02 UTC, pjohans commented on src/components/ffu/CreateListener.js
> +import { useEffect } from "react";
@file ..

2023-10-24 07:03 UTC, pjohans commented on src/components/profile/myLibrariesPage/addLibraryButton/AddLibraryButton.js
> +import Translate from "@/components/base/translate/Translate";
@file ...

2023-10-24 09:48 UTC, jonaspraem approved these changes

2023-10-24 11:23 UTC, merged