base component
DBCDK/bibliotekdk-next-frontend pull request #277
Opened 2021-12-14 11:08 UTC by pjohans

2021-12-14 12:54 UTC, mtni requested changes
Se kommentar

2021-12-14 12:54 UTC, mtni commented on src/components/base/tjooltjip/Tjooltjip.js
> +export default function TjoolTjip({ placement = "bottom", labelToTranslate }) {
:D :D :D

2021-12-14 12:54 UTC, mtni commented on src/components/base/tjooltjip/Tjooltjip.js
> +import "bootstrap/dist/css/bootstrap.min.css";
Den her må ikke importeres Den indeholder alt bootstrap css (som vi kun bruger 5% af). Du skal istedet indkommentere den pågældende scss fil i `src/scss/custom-bootstrap` som ligger her https://github.com/DBCDK/bibliotekdk-next-frontend/blob/master/src/scss/custom-bootstrap.scss

2021-12-17 11:54 UTC, mtni approved these changes

2021-12-17 11:54 UTC, mtni commented on src/components/base/tjooltjip/TjoolTjip.module.css
>      padding: .375rem .75rem;
Hvorfor bruger du rem her?

2021-12-17 11:54 UTC, mtni commented on src/components/_modal/pages/order/Order.module.css
> +  top: 5px;
Er der en grund til du bruger 5px? og ikke vores standart var(--pt05)?

2021-12-17 12:00 UTC, pjohans commented on src/components/base/tjooltjip/TjoolTjip.module.css
>      padding: .375rem .75rem;
copy paste ...

2021-12-17 12:00 UTC, pjohans commented on src/components/_modal/pages/order/Order.module.css
> +  top: 5px;
jo

2021-12-17 12:05 UTC, merged