Bibdk2021 1443 redirect med workid
DBCDK/bibliotekdk-next-frontend pull request #673
Opened 2023-04-17 15:20 UTC by akri-dbcdk

2023-04-18 05:58 UTC, pjohans commented on next.config.js
> +      {
denher er der ikke nogen der har bedt om - væk med den

2023-04-18 05:59 UTC, mtni requested changes

2023-04-18 05:59 UTC, mtni commented on next.config.js
> +        destination: "/materiale/titel_skaber/work-of:workId",
Så kommer der vel bare til at stå titel_skaber oppe i url'en?

2023-04-19 07:39 UTC, pjohans commented on src/pages/materiale/[title_author]/[workId].js
> +  useEffect(() => {
er det nu også nødvendigt med useEffect .. kan man ikke checke urlen uden?

2023-04-19 07:41 UTC, pjohans commented on src/pages/materiale/[title_author]/[workId].js
> + * Extract fixed url for getInitialProps to fix the url when the title_author is mucked up
godt husket :)  - at vi skal have den med serverside

2023-04-19 09:29 UTC, merged