Bibdk2021 1603 smajusteringer til mobilvisning under udgaver
DBCDK/bibliotekdk-next-frontend pull request #758
Opened 2023-06-20 11:05 UTC by akri-dbcdk

2023-06-20 11:38 UTC, pjohans commented on src/components/work/keywords/Keywords.js
> +      {subjects?.map((subject, index) => {
detder var dbcVerified .. er du sikker på at det er rigtigt ?

2023-06-20 11:41 UTC, pjohans commented on src/lib/manifestationParser.js
> +      <FlatSubjectsForFullManifestation
er det nu en god ide at rode sådan nogen jsx ting ind i manifestationsparseren ?

2023-06-20 11:42 UTC, pjohans requested changes
et par kommentarer

2023-06-22 06:25 UTC, pjohans commented on src/components/work/keywords/Keywords.js
> +      {subjects?.map((subject, index) => {
fuck dig per -

2023-06-22 06:38 UTC, akri-dbcdk commented
Per godkendte denne verbalt

2023-06-22 06:38 UTC, merged