Bibdk2021 1511 parts contributors
DBCDK/bibliotekdk-next-frontend pull request #766
Opened 2023-06-21 14:19 UTC by pjohans

2023-06-21 15:02 UTC, akri-dbcdk requested changes

2023-06-22 05:35 UTC, pjohans commented on src/components/manifestationparts/ManifestationParts.js
> +              {part?.playingTime || ""}
yes - præcis - jeg vil gerne altid have et element i midten - tomt eller ej

2023-06-22 05:37 UTC, pjohans commented on src/components/manifestationparts/ManifestationParts.module.css
> +.manifestionlist li{
.. men når nu alle de andre hedder manifestationlist .. med lille l ?

2023-06-22 05:44 UTC, pjohans commented on src/components/manifestationparts/ManifestationParts.js
> +  const contributorsDisplay = (part) => {
done

2023-06-22 05:44 UTC, pjohans commented on src/components/manifestationparts/ManifestationParts.js
> +      part?.creatorsFromDescription?.join(", ");
done

2023-06-22 05:50 UTC, pjohans commented on src/components/manifestationparts/ManifestationParts.js
> +            {contributorsDisplay(part) && contributorsDisplay(part)}
check - done

2023-06-22 05:53 UTC, merged