Bibdk2021 84 helpmenu
DBCDK/bibliotekdk-next-frontend pull request #93
Opened 2021-03-11 11:47 UTC by pjohans

første skud

2021-03-11 15:11 UTC, mtni reviewed
:+1:

2021-03-11 15:11 UTC, mtni commented on src/pages/helptexts/[helptxtId].js
> +/**
Skal siden ikke hedde noget på dansk? og evt. noget med titlen i som vi gør på de alm. artikler?

2021-03-11 15:11 UTC, mtni commented on src/pages/helptexts/[helptxtId].js
> +    <React.Fragment>
Skal der være en Head som kan beskrive siden? og hvad med jsonld? Er disse typer af artikler noget vi gerne vil have indexeret hos google? -> kunne folk ikke finde på at google efter løsningerne? :thinking:

2021-03-11 15:23 UTC, pjohans commented on src/components/helptexts/HelpTextMenu.js
> +  });
det var da en god ide

2021-03-11 15:24 UTC, pjohans commented on src/components/helptexts/HelpTextMenu.js
> +            : ""
jamen jeg er helst fri for deder backticks

2021-03-11 15:24 UTC, pjohans commented on src/pages/helptexts/[helptxtId].js
> +/**
det har du ret i

2021-03-11 15:24 UTC, pjohans commented on src/pages/helptexts/[helptxtId].js
> +    <React.Fragment>
også godt set

2021-03-12 06:37 UTC, kfudbc requested changes
Helt overordnet er det super godt arbejde! Der er kun nogle få detaljer jeg har kommentarer til, og så synes jeg også det er nogle gode pointer @mtni har.

2021-03-12 06:37 UTC, kfudbc commented on next.config.js
> +        "https://alfa-api.bibliotek.dk/graphql",
Vil vi ikke køre mod staging miljøerne når vi udvikler lokalt?

2021-03-12 06:37 UTC, kfudbc commented on src/components/helptexts/HelpText.js
> +export function getAhelpText({ helpTextID }) {
synes at denne custom hook er overflødig. Vil ikke mene at vi bør eksportere en custom hook fra helptext-filen

2021-03-12 06:37 UTC, kfudbc commented on src/components/helptexts/HelpText.js
> +export default function Wrapper({ helpTextID }) {
Vi kalder denne funktion "Wrap" de andre steder (medmindre vi ikke har fået rettet alle steder)

2021-03-12 06:37 UTC, kfudbc commented on src/components/helptexts/HelpText.js
> +}
Der mangler lidt PropTypes til Wrap og HelpText

2021-03-12 06:37 UTC, kfudbc commented on src/components/helptexts/HelpTexts.stories.js
> +  title: "helptext/Helptext",
måske kunne titlen være help/HelpText, for så kan vi andre også smide vores ind i help/blah og få det grupperet samlet

2021-03-12 06:37 UTC, kfudbc commented on src/components/helptexts/menu/HelpTextMenu.js
> +export default function Wrapper({ helpTextID }) {
wrap + proptypes

2021-03-12 06:37 UTC, kfudbc commented on src/components/helptexts/page/Page.js
> +          <Title type="title4">Hjælp og vejledninger</Title>
translate

2021-03-12 11:35 UTC, kfudbc approved these changes
:1st_place_medal:

2021-03-12 11:45 UTC, merged