Bibdk2021 1347 bookmark sort
DBCDK/bibliotekdk-next-frontend pull request #935
Opened 2023-09-26 09:08 UTC by YousefMohsen

2023-09-26 09:41 UTC, kiscdbc commented on src/components/base/forms/list/List.module.css
> +  height: 16px;
var(--pt2) :-)

2023-09-26 09:43 UTC, kiscdbc commented on src/components/base/translate/Translate.json
> +        "en": "AlphabeticalOrder - title"
måske kun "en": "Alphabetical- title"

2023-09-26 09:43 UTC, kiscdbc commented on src/components/base/translate/Translate.json
> +        "en": "Latest added"
"most recently added"?

2023-09-26 09:44 UTC, kiscdbc approved these changes
👍

2023-09-28 06:52 UTC, jonaspraem requested changes

2023-09-28 06:52 UTC, jonaspraem commented on src/lib/api/bookmarks.fragments.js
> +export const fetchAll = ({ sortBy }) => {
kunne godt have en default her

2023-09-28 06:52 UTC, jonaspraem commented on src/components/work/overview/bookmarkDropdown/BookmarkDropdown.js
>        materialType: material[0],
Skal vi ikke også kunne sortere efter date added? det skal vel i cookien

2023-10-02 06:59 UTC, YousefMohsen commented on src/lib/api/bookmarks.fragments.js
> +export const fetchAll = ({ sortBy }) => {
Den har createdAt som default i userdata service

2023-10-02 06:59 UTC, YousefMohsen commented on src/components/work/overview/bookmarkDropdown/BookmarkDropdown.js
>        materialType: material[0],
Har lavet noget hvor den sortere efter createdAt i cookie

2023-10-02 07:47 UTC, jonaspraem approved these changes
Nogle ting der hører til i utils, ellers good

2023-10-02 07:47 UTC, jonaspraem commented on src/components/hooks/useBookmarks.js
> +   * @param {*} sortDirection can be either asc or desc
Vil tro der er en util funktion til at sortere datoer, ellers skal denne nok ind i util

2023-10-02 07:47 UTC, jonaspraem commented on src/components/hooks/useBookmarks.js
> +   * @param {*} sortDirection can be either asc or desc
Vil tro der er en util funktion til at sortere alfabetisk, ellers skal denne nok ind i util

2023-10-02 08:51 UTC, merged