scroll to top + 20 per page
DBCDK/bibliotekdk-next-frontend pull request #991
Opened 2023-10-12 08:42 UTC by YousefMohsen

2023-10-12 15:01 UTC, jonaspraem requested changes

2023-10-12 15:01 UTC, jonaspraem commented on src/components/hooks/useBookmarks.js
> +const itemsPerPage = 20;
Statisk constant - skrives med all caps ITEMS_PER_PAGE

2023-10-13 07:15 UTC, YousefMohsen commented on src/components/hooks/useBookmarks.js
> +const itemsPerPage = 20;
fixed

2023-10-13 10:55 UTC, jonaspraem approved these changes

2023-10-16 07:48 UTC, merged